env:
  browser: true
  es6: true
  jquery: true
extends:
  - 'plugin:vue/essential'
  - 'plugin:prettier/recommended'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
globals:
  process: false
rules:
  no-console: 0
  no-unused-vars:
    - error
    - args: none
